// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc9JLbfyDKA_uHrqij4cab_Az6doIa4Hw',
    appId: '1:797299833740:web:a51f6f39df379b556d34a9',
    messagingSenderId: '797299833740',
    projectId: 'nutrition-assistance-firebase',
    authDomain: 'nutrition-assistance-firebase.firebaseapp.com',
    storageBucket: 'nutrition-assistance-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUv9sGLgKy3M08sSnkICo2ml7AF02f9wk',
    appId: '1:797299833740:android:5731a2b00f2466e96d34a9',
    messagingSenderId: '797299833740',
    projectId: 'nutrition-assistance-firebase',
    storageBucket: 'nutrition-assistance-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoCvNRxxTtbTFDsFAPPsiLFubIbuZ2i5A',
    appId: '1:797299833740:ios:72817d07becb38ee6d34a9',
    messagingSenderId: '797299833740',
    projectId: 'nutrition-assistance-firebase',
    storageBucket: 'nutrition-assistance-firebase.appspot.com',
    iosBundleId: 'com.example.projectNutrition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoCvNRxxTtbTFDsFAPPsiLFubIbuZ2i5A',
    appId: '1:797299833740:ios:72817d07becb38ee6d34a9',
    messagingSenderId: '797299833740',
    projectId: 'nutrition-assistance-firebase',
    storageBucket: 'nutrition-assistance-firebase.appspot.com',
    iosBundleId: 'com.example.projectNutrition',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc9JLbfyDKA_uHrqij4cab_Az6doIa4Hw',
    appId: '1:797299833740:web:7f52fc59762179a06d34a9',
    messagingSenderId: '797299833740',
    projectId: 'nutrition-assistance-firebase',
    authDomain: 'nutrition-assistance-firebase.firebaseapp.com',
    storageBucket: 'nutrition-assistance-firebase.appspot.com',
  );

}